### ISSUE TITLE
Data Source 

### ISSUE THREAD

**Issue by Columbine21** [imessam/MARNN-paper-implementation#1]
Hi, where did you get the original dataset? (auido.pkl...)

Many thx!

**Comment by imessam** [comment]
The dataset is the CMU-MOSI dataset and it has the extracted features from the raw data , so you can use it directly without extracting features from the raw data.
But you have to preprocess the features first to be able to use it as an input to the model where the shape of the input data is
 (no. videos, no. utterances for each video, dim of features for each modal)

http://multicomp.cs.cmu.edu/resources/cmu-mosi-dataset/

I hope the it helps.

**Comment by Columbine21** [comment]
Thx for your reply!
